/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    GlobalToast: typeof import('./src/components/GlobalToast.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconFallback: typeof import('./src/components/IconFallback.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartIcon: typeof import('./src/components/SmartIcon.vue')['default']
  }
}
