/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/categories': RouteRecordInfo<'/categories', '/categories', Record<never, never>, Record<never, never>>,
    '/debtors': RouteRecordInfo<'/debtors', '/debtors', Record<never, never>, Record<never, never>>,
    '/engineers': RouteRecordInfo<'/engineers', '/engineers', Record<never, never>, Record<never, never>>,
    '/equipment-details': RouteRecordInfo<'/equipment-details', '/equipment-details', Record<never, never>, Record<never, never>>,
    '/example-design-system': RouteRecordInfo<'/example-design-system', '/example-design-system', Record<never, never>, Record<never, never>>,
    '/expense-types': RouteRecordInfo<'/expense-types', '/expense-types', Record<never, never>, Record<never, never>>,
    '/expenses': RouteRecordInfo<'/expenses', '/expenses', Record<never, never>, Record<never, never>>,
    '/human-resources': RouteRecordInfo<'/human-resources', '/human-resources', Record<never, never>, Record<never, never>>,
    '/income': RouteRecordInfo<'/income', '/income', Record<never, never>, Record<never, never>>,
    '/inventory': RouteRecordInfo<'/inventory', '/inventory', Record<never, never>, Record<never, never>>,
    '/labor-details': RouteRecordInfo<'/labor-details', '/labor-details', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/materials-expenses-details': RouteRecordInfo<'/materials-expenses-details', '/materials-expenses-details', Record<never, never>, Record<never, never>>,
    '/project-details': RouteRecordInfo<'/project-details', '/project-details', Record<never, never>, Record<never, never>>,
    '/project-expenses': RouteRecordInfo<'/project-expenses', '/project-expenses', Record<never, never>, Record<never, never>>,
    '/project-management': RouteRecordInfo<'/project-management', '/project-management', Record<never, never>, Record<never, never>>,
    '/purchases': RouteRecordInfo<'/purchases', '/purchases', Record<never, never>, Record<never, never>>,
    '/sales': RouteRecordInfo<'/sales', '/sales', Record<never, never>, Record<never, never>>,
    '/task-management': RouteRecordInfo<'/task-management', '/task-management', Record<never, never>, Record<never, never>>,
    '/team-management': RouteRecordInfo<'/team-management', '/team-management', Record<never, never>, Record<never, never>>,
    '/test-dialog': RouteRecordInfo<'/test-dialog', '/test-dialog', Record<never, never>, Record<never, never>>,
    '/test-icons-final': RouteRecordInfo<'/test-icons-final', '/test-icons-final', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
    '/work-day-details': RouteRecordInfo<'/work-day-details', '/work-day-details', Record<never, never>, Record<never, never>>,
    '/work-day-details-fixed': RouteRecordInfo<'/work-day-details-fixed', '/work-day-details-fixed', Record<never, never>, Record<never, never>>,
    '/work-day-details-simple': RouteRecordInfo<'/work-day-details-simple', '/work-day-details-simple', Record<never, never>, Record<never, never>>,
    '/work-days': RouteRecordInfo<'/work-days', '/work-days', Record<never, never>, Record<never, never>>,
    '/working-day-details': RouteRecordInfo<'/working-day-details', '/working-day-details', Record<never, never>, Record<never, never>>,
  }
}
