/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/categories': RouteRecordInfo<'/categories', '/categories', Record<never, never>, Record<never, never>>,
    '/debtors': RouteRecordInfo<'/debtors', '/debtors', Record<never, never>, Record<never, never>>,
    '/equipment-details': RouteRecordInfo<'/equipment-details', '/equipment-details', Record<never, never>, Record<never, never>>,
    '/expenses': RouteRecordInfo<'/expenses', '/expenses', Record<never, never>, Record<never, never>>,
    '/income': RouteRecordInfo<'/income', '/income', Record<never, never>, Record<never, never>>,
    '/labor-details': RouteRecordInfo<'/labor-details', '/labor-details', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/materials-expenses': RouteRecordInfo<'/materials-expenses', '/materials-expenses', Record<never, never>, Record<never, never>>,
    '/pages': RouteRecordInfo<'/pages', '/pages', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
    '/roles': RouteRecordInfo<'/roles', '/roles', Record<never, never>, Record<never, never>>,
    '/tasks': RouteRecordInfo<'/tasks', '/tasks', Record<never, never>, Record<never, never>>,
    '/team-members': RouteRecordInfo<'/team-members', '/team-members', Record<never, never>, Record<never, never>>,
    '/test-icons-final': RouteRecordInfo<'/test-icons-final', '/test-icons-final', Record<never, never>, Record<never, never>>,
    '/unauthorized': RouteRecordInfo<'/unauthorized', '/unauthorized', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
    '/work-day-details': RouteRecordInfo<'/work-day-details', '/work-day-details', Record<never, never>, Record<never, never>>,
    '/work-days': RouteRecordInfo<'/work-days', '/work-days', Record<never, never>, Record<never, never>>,
  }
}
